### ISSUE TITLE
UAI impossibles à saisir ou sélectionner

### ISSUE THREAD

**Issue by gasilber** [mission-apprentissage/referentiel#103]
2 exemples de saisie d'UAI qui bloque en front office (en cause : un nombre trop important d'UAI potentielles proposées ?)

- SIRET : 88087198300024 : ne porte pas le bon UAI. Le bon UAI est le 0922791J mais impossible de cliquer sur « autre » pour saisir cet UAI
- SIRET : 13001835100010 : impossible de choisir l'UAI souhaitée (0333357V), qui est pourtant dans la liste des UAI potentielles

**Comment by gasilber** [comment]
Déployé en développement et production.

**Comment by FlavieSauvebois** [comment]
Ticket qui pourra être clôturé quand les corrections seront possibles sous Firefox. 
En attendant, j'ai pu faire les corrections sous Chrome donc c'est tout bon dans le Référentiel.

**Comment by yohanngab** [comment]
Voila le fix pour firefox : https://github.com/mission-apprentissage/referentiel/pull/134 :)
Tout fonctionne sur safari/chrome/firefox de mon côté!

**Comment by gasilber** [comment]
Déployé en production
