### ISSUE TITLE
Récupération de l'UAI de lieu de formation dans le référentiel

### ISSUE THREAD

**Issue by sbenfares** [mission-apprentissage/referentiel#113]
- [x] Synchro @QuentinPetel sur récupération uai de formation
- [x] Création de compte d'accès référentiel
- [x] PR coté référentiel cf @gasilber 
- [ ] Update modèle coté TDB

**Comment by FlavieSauvebois** [comment]
Bonjour, je ré-ouvre ce ticket car avec Anne nous aurions besoin de savoir combien de lieux de formation différents ne sont pas porteurs d’une UAI dans le Référentiel ?
Est-ce qu'il serait possible d'ajouter ces données (adresse lieux de formation + UAI vide ou complète) dans le fichier Excel d'export ?
