### ISSUE TITLE
Extension de la date de validité des "liens magiques" 

### ISSUE THREAD

**Issue by gasilber** [mission-apprentissage/referentiel#115]
Les liens générés permettant de se connecter au référentiel ont une date de validité fixe.
Afin de prolonger la date de validité le temps qu'un système d'identifiants stockés en base soit mis en place, un hack peut-être mis en place lors de la récupération et le stockage du token afin de mettre une date plus longue.

Voir: https://github.com/mission-apprentissage/referentiel/blob/main/ui/src/common/ApiProvider.jsx#L29

Solution temporaire avant l'implémentation de #116

**Comment by FlavieSauvebois** [comment]
D'après Yohann les liens magiques expireraient le 05/09/2023
