### ISSUE TITLE
Organisme sans académie

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#119]
Il faut que l’on creuse ce problème au sein du référentiel.
Nous avons aujourd’hui 29 OF sans académie au sein du référentiel mais qui sont Qualiopi OUI. Il faudrait donc qu’on les expertise mais impossible de le faire car ils ne remontent dans aucune académie.  
Il y en a 2 qui ont une UAI validée. Comment cela a-t-il pu se faire et par qui ? C’est en dur dans le code pour ces deux OF là (50215377800019 / 50215377800027) ?

**Comment by gasilber** [comment]
Avec la commande de modification manuelle introduite pour #117, on doit pouvoir mettre ces UAI en dur.

**Comment by FlavieSauvebois** [comment]
Couples à inscrire en dur dans le code :
49386136300080 - 0755908P
83415492400015 - 0756195B 
J'attends d'autres retours donc peut-être attendre avant intégration

**Comment by FlavieSauvebois** [comment]
nouveau couple à inscrire en dur : 
83035903000012 - 9711305S
J'attends encore un retour.

**Comment by FlavieSauvebois** [comment]
Voici le dernier couple à inscrire en dur dans le Référentiel : 
43964416200034  - 0134303G

Je n'attends plus de retours donc l’inscription en manuelle de ces UAI peut être effectuée.

**Comment by FlavieSauvebois** [comment]
Merci, je clos le ticket. 
Il faudra toutefois penser à relancer ce contrôle qualité de temps en temps.

**Comment by FlavieSauvebois** [comment]
Hello, je réouvre ce ticket car j'ai besoin d'ajouter un UAI sur un OF sans académie. 
Je vois que vous pouvez le faire en dur via une commande. 
Voici le couple : 18130002100019 - 0133527N
C'est assez urgent. Merci d'avance pour votre intervention.

**Comment by gasilber** [comment]
Modification manuelle en production:

```bash
sudo -s
docker exec referentiel_server yarn cli modify 18130002100019 0133527N
docker exec referentiel_server yarn cli consolidate --siret 18130002100019 
```
