### ISSUE TITLE
Fiabilisation - Identification des pb de collecte des uais lieux de formation

### ISSUE THREAD

**Issue by sbenfares** [mission-apprentissage/referentiel#123]
Les UAI des lieux de formation dans le référentiel ne sont pas toujours fiables.
Vu avec @QuentinPetel on pars du principe que les UAI de formation traitées par les instructeurs sont fiables et les autres non.
Du coup dans le référentiel je prévois de : 

- [x] Remonter les champs **parcoursup_statut** et **affelnet_statut**
- [x] Ajouter une information **uai_lieu_fiable** en fonction de la valeurs des champs **affelnet_statut** / **parcoursup_statut**
- [x] N'afficher dans l'UI que les lieux ayant le champ **uai_lieu_fiable  = true**

Ensuite coté TDB on remontera ce champ uai_lieu_fiable et dans le script de fiab on filtrera sur les lieux ayant uai_lieu_fiable  = true.

**Comment by gasilber** [comment]
?

**Comment by sbenfares** [comment]
Bonjour @gasilber nous avons identifié un pb de collecte des UAI de lieux de formation dans le référentiel, je me suis permis de créer une carte pour notre gestion. Je vais pe la déplacer

**Comment by gasilber** [comment]
Bonjour @sbenfares , ok, merci pour l'info
