### ISSUE TITLE
Problématique des doublons des lieux des organismes du référentiel

### ISSUE THREAD

**Issue by sbenfares** [mission-apprentissage/referentiel#129]
Exemple : Responsable    CFAA DU LOT  (46500 Gramat)   SIRET : 194 604 906 00041  / UAI : 0460654L

**Comment by sbenfares** [comment]
En attente déploiement référentiel

**Comment by gasilber** [comment]
Déployé en développement puis en production.

**Comment by FlavieSauvebois** [comment]
Je réactive ce ticket car j'ai l'impression que de nombreux autres organismes sont concernés par cette problématique.
Ex : 88356652300014 / 79906530500036 / 95096966700019 / 77568879902157 ...
Ce n'est que qq exemples, je pense qu'il y en a plein d'autres. 
Le lieux semble s'afficher en double de façon assez systématique. 
Est-ce que cela a un lien avec la récupération des UAI depuis le catalogue public de la DNE (c'est Samir qui avait bossé dessous) ?
Est-ce que vous pouvez regarder ? On en parle jeudi prochain
Merci. Flavie

**Comment by FlavieSauvebois** [comment]
Pb d'affichage qui n'est plus visible ce jour (le 5/10/2023)
