### ISSUE TITLE
FRONT : Modification de l'adresse de contact sur le site

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#139]
Ce ticket concerne le Front donc je pense que c'est Yohann qui pourra intervenir. 

Il faudrait modifier l'adresse de contact sur le page suivante du site : https://referentiel.apprentissage.onisep.fr/corrections
Dans la partie" un organisme ne devrait pas être présent dans le référentiel"
=> remplacer l'adresse présente par : referentiel-uai-siret@onisep.fr

Merci Flavie

**Comment by yohanngab** [comment]
Bonjour,

Voici la PR correspondante https://github.com/mission-apprentissage/referentiel/pull/142

Merci!

**Comment by FlavieSauvebois** [comment]
Du coup Yohann tu as prévu de merger ou tu attends un retour de Georges-André ?

**Comment by gasilber** [comment]
Bonjour Flavie, c’est de mon côté, je vais déployer dans la soirée.

**Comment by FlavieSauvebois** [comment]
Ok super, je ne savais pas qui avait la main. Merci pour ton retour
