### ISSUE TITLE
FRONT : lien vers fiche sur data.gouv

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#141]
Sur une fiche établissement qui a pour source la Liste publique des organismes de formation, lorsque l'on clique sur "Afficher les données de la liste publique des organismes de formation", dans la fenêtre pop up qui s'ouvre, le lien vers "Consulter la fiche - Data.gouv" ne fonctionne pas 
Ex : https://referentiel.preprod.onisep.fr/organismes/91208413400010

Par contre, je ne sais pas vers quoi doit pointer ce lien ? Est-ce qu'on a moyen de retrouver vers quoi cela pointait quand ça fonctionnait ?

**Comment by FlavieSauvebois** [comment]
J'ai questionné Anne pour savoir vers quoi pointait auparavant ce lien. 
Je te confirme Yohann qu'il s'agit bien du lien suivant dont tu avais trouvé la trace dans le code : https://www.data.gouv.fr/fr/datasets/liste-publique-des-organismes-de-formation-l-6351-7-1-du-code-du-travail/

Peux-tu donc le rétablir pour tous les organismes dont la source est la Liste publique des Organismes de formation ?

On avait également évoqué lors de notre dernière visio l'Annuaire des entreprises et la possibilité de faire pointer ce lien sur la fiche détaillée de l'OF sur ce site : https://annuaire-entreprises.data.gouv.fr/entreprise/898208764
Apparemment via le SIRET ça ne serait pas trop difficile à mettre en place. A réfléchir, mais pour l’instant ce lien n’existe que pour les OF dont la source est la Liste publique des OF, donc ça ne concerne pas tous les OF du Référentiel. On en reparle lors de notre prochain stand up.

**Comment by yohanngab** [comment]
Bonjour,

Voici la [PR](https://github.com/mission-apprentissage/referentiel/pull/147) pour remettre à l'état précédent, en attendant une décision sur les liens annuaires.
