### ISSUE TITLE
FRONT - Coquille sur le site

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#144]
Bonjour Yohann, 

Davis m'a signalé une coquille sur le site sur la page suivante : https://referentiel.apprentissage.onisep.fr/construction/import
Dans le titre : Import et comp**li**lation des données

Peux-tu la corriger facilement ?

Bonne journée. Flavie

**Comment by FlavieSauvebois** [comment]
Après je vais avoir d'autres corrections à faire sur cette page au niveau des contenus donc peut-être qu'il est préférable d'attendre que je liste toutes les modifs avant de les mettre en production ? Vous me direz.

**Comment by yohanngab** [comment]
Bonjour!
J'ai corrigé la première coquille et j'ai ouvert une [PR](https://github.com/mission-apprentissage/referentiel/pull/146) pour y ajouter les autres, n'hésite pas à les lister ici.
