### ISSUE TITLE
Code communes et coordonnées GPS des OF présents dans le Référentiel

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#151]
Toujours suite à mon échange avec la BPE, j'aurai besoin de savoir si l'on dispose en back office des données suivantes pour les organismes de formation que nous collectons ? : 
- code commune issus du Code officiel géographique (COG) 
- coordonnées GPS ou Lambert -> le pôle BPE pourrait les expertiser au regard des coordonnées calculées par l’Insee. Les résultat seraient transmis à l’Onisep

**Comment by CorreiaDavid** [comment]
Si le Code officiel géographique (COG) correspond bien au code INSEE commune, il est disponible dans la table `organismes`. En ce qui concerne les coordonnées GPS, elles sont aussi disponibles au format degré décimaux.

**Comment by FlavieSauvebois** [comment]
Ok merci David pour ton retour.
