### ISSUE TITLE
URGENT - Relation erronée entre les organismes 

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#156]
Ce ticket est peut-être en lien avec le ticket 152. 
Un organisme nous signale une relation erronée dans sa fiche OF sur le Référentiel : https://referentiel.apprentissage.onisep.fr/organismes/30343537400010
Il apparait en effet comme étant lié à l'organisme Formation et Métier en tant qu'organisme formateur de ce dernier.
Or, l'organisme en question nous affirme n'avoir aucune relation avec Formation et Métier.
Cette relation erronée est affichée dans le Référentiel mais elle remonte également dans le Tableau de bord de l'Apprentissage. 

Dans le Référentiel, les relations entre les organismes sont déduites de la manière dont est déclarée l'offre de formation auprès du Carif. 
Or, pour cet organisme voici comment l'offre est déclarée : https://catalogue-apprentissage.intercariforef.org/recherche/formations?SEARCH=%2277555830700093%22&defaultMode=advanced&qb=%255B%257B%2522field%2522%253A%2522etablissement_gestionnaire_siret.keyword%2522%252C%2522operator%2522%253A%2522%253D%253D%253D%2522%252C%2522value%2522%253A%252230343537400010%2522%252C%2522combinator%2522%253A%2522AND%2522%252C%2522index%2522%253A0%252C%2522key%2522%253A%252287e13048-452c-4b3f-8a01-01038e183538%2522%257D%252C%257B%2522field%2522%253A%2522etablissement_formateur_siret.keyword%2522%252C%2522operator%2522%253A%2522%253D%253D%253D%2522%252C%2522value%2522%253A%252230343537400010%2522%252C%2522combinator%2522%253A%2522OR%2522%252C%2522index%2522%253A1%252C%2522key%2522%253A%2522ec62f771-90c7-4030-83a6-503dbcc4e47b%2522%257D%255D

=> L'organisme Formation Métier ne figure nulle part et n'est pas lié à l'offre de cet organisme.

Il faudrait donc regarder dans le code et voir pourquoi cette relation entre les 2 organismes est déduite alors qu'elle ne devrait pas l'être. 
Je te laisse regarder et revenir vers moi si tu as besoin de précisions.

**Comment by gasilber** [comment]
Ces deux organismes sont en relation à cause du fichier (ancien) IDEO2:

```javascript
db.organismes.findOne({siret:"30343537400010"})`
```

```json
	{"relations" : [
		{
			"type" : "formateur->responsable",
			"siret" : "77555830700093",
			"label" : "Formation et Mï¿½tier, CFA rï¿½gional de la citï¿½ technique",
			"referentiel" : true,
			"sources" : [
				"ideo2"
			],
			"date_collecte" : ISODate("2023-09-22T04:07:26.601Z")
		}
	]}
```

**Comment by FlavieSauvebois** [comment]
Quand tu dis que la relation est purgée quand elle a plus de 7 jours, cela veut dire que la relation est mise à jour tous les 7 jours ? Or comme la le fichier source ne bouge pas, elle ne change pas ? C'est bien ça ?
Je serai donc d'avis de supprimer ce fichier Idéo2 dans la déduction des relations entre les OF car c'est un vieux fichier avec des données certainement erronées. Est-ce qu'on ne pourrait pas remplacer ce fichier par les données Idéo2 de l'entrepôt ?

**Comment by gasilber** [comment]
> Quand tu dis que la relation est purgée quand elle a plus de 7 jours, cela veut dire que la relation est mise à jour tous les 7 jours ? Or comme la le fichier source ne bouge pas, elle ne change pas ? C'est bien ça ?

Comme le fichier source ne bouge pas, elle ne change pas (elle est en fait "mise-à-jour" tous les jours).

> Je serai donc d'avis de supprimer ce fichier Idéo2 dans la déduction des relations entre les OF car c'est un vieux fichier avec des données certainement erronées. Est-ce qu'on ne pourrait pas remplacer ce fichier par les données Idéo2 de l'entrepôt ?

Je peux effectivement temporairement ne pas tenir compte de cette source pour les relations. Nous pourrons remettre ceci en fonction quand on sera branché à l'entrepôt.

**Comment by gasilber** [comment]
J'ai supprimé la création de relations via ideo2.

**Comment by FlavieSauvebois** [comment]
Super merci pour ton retour et ton intervention. 
Par contre, est-ce qu'il serait possible de nettoyer l'affichage de cette relation erronée sur le front car elle est tjs visible : https://referentiel.apprentissage.onisep.fr/organismes/30343537400010/relations

**Comment by FlavieSauvebois** [comment]
L'affichage de la relation erronée s'est nettoyé tout seul car la relation entre les OF n'est plus apparue pendant plus de 7 jours donc elle s'est supprimée automatiquement. Je clos
