### ISSUE TITLE
MAJ données INSEE : OF dont le nom d'enseigne s'affiche toujours 

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#177]
Il faudrait regarder pourquoi ce CFA a toujours son "nom d’enseigne" renseigné au sein du Référentiel alors que sur la base INSEE il ne communique plus de nom d'enseigne : [](https://referentiel.apprentissage.onisep.fr/organismes/89835392500016)

Peut-être que nous gardons en cache certaines informations en cas de down de l'API entreprise et dans ce cas combien de temps ? Ou alors est-ce que les informations sont mises à jour qu'en cas de fermeture ou de changement de raison sociale et non lorsqu'il s'agit d'un autre type de modification ?

**Comment by gasilber** [comment]
Intervention manuelle:

```bash
organismes = db.organismes
organismes.updateOne(
  {"siret":"89835392500016"},
  { $unset: {"enseigne": ""}}
);
```

Je ne sais pas pourquoi cet établissement n'a pas été mis à jour.
