### ISSUE TITLE
OF à supprimer du Référentiel - 34906645600022 

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#179]
Bonjour, 
Il faudrait supprimer l'OF suivant du Référentiel car il ne propose plus d'apprentissage : FEDER DEPART DES MAISONS FAMILIALES de Beaucouzé – UAI : 0492193T – SIRET : 34906645600022 

Il n'est plus présent dans le Catalogue Apprentissage, ni dans la liste publique des OF. Je pense qu'il continue d'être présent dans le Référentiel car son SIRET doit toujours être présent dans le vieux fichier SIFA-RAMSESE. 

Il faut donc le supprimer manuellement

**Comment by gasilber** [comment]
C'est curieux car je ne le trouve nulle part, y compris dans les fichiers SIFA-RAMSESE.

Je vais l'effacer de la base et voir si il réapparaît.

**Comment by gasilber** [comment]
```
o = coll.deleteOne({"siret":"34906645600022"})
```

**Comment by gasilber** [comment]
Il est bien dans le fichier SIFA:

```bash
gasilber@toupatou:~/Dropbox/data_cons/source_data/rofa$ grep 34906645600022 *.csv
liste_etab_SIA_Dares_v4.csv:0491828W;34906645600022;FEDER DEPART DES MAISON FAMILIALES;BEAUCOUZE;49070;FAUX;0;0;6;5;5
liste_etab_SIA_Dares_v4.csv:0491941U;34906645600022;FEDERATION DEP DES MFR DU 49;BEAUCOUZE;49070;FAUX;1;1;0;0;0
liste_etab_SIA_Dares_v4.csv:0492193T;34906645600022;FEDER DEPART DES MAISON FAMILIALES;BEAUCOUZE;49070;FAUX;3;2;1;1;1
```

(je n'avais pas fait le test sur SIFA_v4 que je n'avais pas en local)

**Comment by FlavieSauvebois** [comment]
Hello, je me rends compte que cet OF est de nouveau présent dans le Référentiel. 
Est-ce que tu peux regarder pourquoi il revient ?

**Comment by gasilber** [comment]
Il me semblait l'avoir supprimé de SIFA-RAMSESE. Nouvelle suppression et re-upload du CSV de SIFA-RAMSESE supprimé.

**Comment by gasilber** [comment]
Testé ce matin: https://referentiel.apprentissage.onisep.fr/organismes/34906645600022

L'organisme n'est pas réapparu après la suppression d'hier.
