### ISSUE TITLE
Ajout Logo ONISEP sur le Front Office

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#180]
A voir ensemble

**Comment by gasilber** [comment]
![logo](https://github.com/mission-apprentissage/referentiel/assets/1884223/50f28199-01fd-4dc0-bd7f-012c3c23ccf5)

**Comment by FlavieSauvebois** [comment]
[Logotype_Onisep_070224.zip](https://github.com/mission-apprentissage/referentiel/files/14259748/Logotype_Onisep_070224.zip)

**Comment by yohanngab** [comment]
Voici la [PR](https://github.com/mission-apprentissage/referentiel/pull/181) qui ajoute le logo et change le nom.
