### ISSUE TITLE
Suppression Ecoles maternelles du Référentiel

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#192]
Serait-il possible de supprimer du Référentiel les 2 écoles maternelles suivantes qui sont remontées car présentes dans le fichier SIFA 2021 : 
- 77643724600023
- 21440109300197

**Comment by gasilber** [comment]
Suppression effectuée en production.

**Comment by FlavieSauvebois** [comment]
Les deux écoles sont de nouveau présentes dans le Référentiel - à corriger

**Comment by gasilber** [comment]
Nouvelle suppression des écoles, et suppression dans le bon fichier SIFA des données en question.
Elles ne devraient plus réapparaitre.

**Comment by FlavieSauvebois** [comment]
Cette fois-ci c'est tout bon, je clos le ticket.
