### ISSUE TITLE
Page accueil du site

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#198]
Est-ce que les données chiffrées sont mises à jour en temps réel ? 
Il contient **97%** d’organismes validés sur le territoire national.
Les **3974** organismes référencés dans le référentiel sont :

Est-ce que la partie sur l'intégration des données ACCE ne serait pas à supprimer en attendant que la récupération des données soit réellement effective ?

**Comment by gasilber** [comment]
Je pense qu'effectivement on peut enlever la mention de la base ACCE dans la description.
Pour la modalité de calcul, je laisse @ldaverio répondre (ingénieur en informatique aux mines et qui nous rejoint sur ce projet).

**Comment by ldaverio** [comment]
Bonjour à tous, je suis très heureux de participer au projet.

Les données en question (nombre d'organismes référencés, et pourcentage d'organismes validés) sont récupérés via un appel à l'API dans le frontend :

https://github.com/mission-apprentissage/referentiel/blob/be34381322b7f3a9c6da3c3dc3f1d0c23390e505/ui/src/accueil/AccueilPage.jsx#L21

Cet appel récupère un objet `stats`avec deux clés, `total` et `valides` :

https://github.com/mission-apprentissage/referentiel/blob/be34381322b7f3a9c6da3c3dc3f1d0c23390e505/ui/src/accueil/AccueilPage.jsx#L43-L44

et :

https://github.com/mission-apprentissage/referentiel/blob/be34381322b7f3a9c6da3c3dc3f1d0c23390e505/ui/src/accueil/AccueilPage.jsx#L50

Côté serveur, les données sont calculées comme suit :

- le nombre total est le nombre d'organismes actifs ayant l'attribut `qualiopi`  à "vrai", et une nature égale à "responsable" ou "responsable formateur" ;

https://github.com/mission-apprentissage/referentiel/blob/be34381322b7f3a9c6da3c3dc3f1d0c23390e505/server/src/http/routes/statsRoutes.js#L38-L42

- les organismes valides sont ceux ayant en outre un `uai` :

https://github.com/mission-apprentissage/referentiel/blob/be34381322b7f3a9c6da3c3dc3f1d0c23390e505/server/src/http/routes/statsRoutes.js#L44-L50

Pour l'instant, je ne peux pas en dire plus, juste identifier le cheminement ayant conduit à ces résultats.

**Comment by FlavieSauvebois** [comment]
Bonjour Laurent, 

Bienvenue dans l'équipe, nous sommes ravis de t'accueillir. 
Merci pour tes explications qui me permettent d'y voir plus clair et de comprendre pourquoi les données chiffrées affichées sur la page d'accueil sont différentes de celles que j'avais en termes de volume. 

Déjà on peut confirmer que la mise à jour des chiffres se fait en temps réels (ou du moins chaque jour) car le nombre d'OF en expertise affichés a bien évolué entre nos deux posts.

Par ailleurs, le chiffre actuel qui est affiché (_Les 3979 organismes référencés dans le référentiel sont_ ) : comptabilise uniquement les OF responsable et responsable formateur qui sont Qualiopi OUI avec un SIRET actif.
Pour que le chiffre soit juste : **il faut simplement ajouter les OF dont la nature est formateur uniquement**. 
On aura alors la volumétrie suivante pour aujourd'hui : 5009 OF
Et il s'agira de la volumétrie exacte car les OF formateurs ont été ajouté dans un second à l'expertise (la correction n'avait donc pas été faite dans le code).

Pour le calcul du % d'OF c'est OK

Nous pourrons reparler de tout ça jeudi lors de notre visio qui a lieu tous les 15 jours. @ldaverio peux-tu me donner ton mail afin que te transfère l’invitation ?

Bonne journée

**Comment by ldaverio** [comment]
Bonjour Flavie,

> Par ailleurs, le chiffre actuel qui est affiché (_Les 3979 organismes référencés dans le référentiel sont_ ) : comptabilise uniquement les OF responsable et responsable formateur qui sont Qualiopi OUI avec un SIRET actif.
> Pour que le chiffre soit juste : **il faut simplement ajouter les OF dont la nature est formateur uniquement**.

Effectivement, si je modifie le code en : 

```
      const validationQuery = {
        etat_administratif: "actif",
        qualiopi: true,
        nature: { $in: ["formateur", "responsable", "responsable_formateur"] },
      };
```

J'obtiens bien le nombre correct.

Mon adresse e-mail est laurent.daverio@minesparis.psl.eu. Je peux me rendre disponible jeudi pour la réunion.

Bonne journée :)

**Comment by ldaverio** [comment]
> J'obtiens bien le nombre correct.

Par contre, sur la page "organismes", en sélectionnant les mêmes critères, je n'obtiens pas la même valeur : `5222` organismes au lieu de `5008` sur mes données de test.

![Screenshot 2024-06-24 at 11-35-50 Référentiel](https://github.com/mission-apprentissage/referentiel/assets/8393625/a5133df6-436b-4a8d-bfca-abecd43b0a3f)

**Comment by FlavieSauvebois** [comment]
C'est normal car sur le site tu ne peux pas faire de filtre sur l'état administratif des OF (actif ou fermé). Seuls ceux qui sont actifs remontent en expertise et sont donc comptabilisés.

**Comment by ldaverio** [comment]
J'ai voulu faire le commit correspondant à la modification demandée. Malheureusement, un test échoue sur ma configuration (MacOS, installation sans Docker) :

https://github.com/mission-apprentissage/referentiel/blob/be34381322b7f3a9c6da3c3dc3f1d0c23390e505/server/tests/http/organismesRoutes-test.js#L213-L218

Le test précédent (recherche des organismes actifs) passe sans problème, la différence est le "é" dans l'URL, ligne `218`. Si je modifie cette ligne en :

```js
const response = await httpClient.get(`/api/v1/organismes?etat_administratif=${encodeURI("fermé")}`);
```

le test passe.

Étant donné que le problème ne semble pas exister sur la configuration "dockerisée" standard, que me suggérez-vous de faire ? Merci d'avance :)

**Comment by ldaverio** [comment]
Si je mets à jour le paquet NPM `axiosist` de la version 0.1.0 (une version 0.x ne devrait pas être utilisée en production, au passage) en version 1.2.0 (la dernière), il y a toujours le même message d'erreur pendant les tests, mais le test réussit. Par conséquent, je peux faire mon commit :)

**Comment by gasilber** [comment]
Modifié et déployé en développement

**Comment by gasilber** [comment]
Déployé en développement: https://dev-referentiel.apprentissage.onisep.fr

**Comment by FlavieSauvebois** [comment]
Ok pour mise en prod
