### ISSUE TITLE
Ajout de la possibilité de rechercher par SIREN sur le moteur de recherche du site

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#202]
Il serait intéressant de pouvoir rechercher les OF appartenant au même groupe sur le Référentiel en intégrant la possibilité de rechercher par SIREN.
Aujourd'hui la recherche peut se faire seulement sur le SIRET. 

Ex : 824092688 00178
          SIREN       SIRET

**Comment by FlavieSauvebois** [comment]
Vu avec David après le Stand-up - voir si on fait 2 recherches (une par SIREN et une par SIREN) ou si une seule suffit est elle recherche à la fois sur le SIRET ou le SIREN - à voir ce qui est le plus simple à mettre en place

**Comment by ldaverio** [comment]
2 questions :

- Y aurait-il un intérêt à proposer de l'autocomplétion, i.e. la recherche commence dès qu'on a tapé un nombre minimal de caractères ? Ce mode de recherche permettrait d'unifier "naturellement" les recherches par SIREN et SIRET.

- Lors de la saisie d'un SIRET, faut-il exiger l'espace blanc entre les deux groupes de chiffres, ou bien un bloc de 14 chiffres sans espaces est-il admissible ?

**Comment by ldaverio** [comment]
Actuellement, le moteur de recherche utilise l'opérateur [$text](https://www.mongodb.com/docs/manual/reference/operator/query/text/) de MongoDB, qui permet de rechercher une valeur dans tous les champs des documents. Malheureusement, cette recherche ne permet de rechercher que des valeurs exactes :( 

https://github.com/mission-apprentissage/referentiel/blob/be34381322b7f3a9c6da3c3dc3f1d0c23390e505/server/src/http/routes/organismesRoutes.js#L113

Il y a plusieurs possibilités pour contourner cette limitation, notamment :

- Remplacer la recherche `$text` par une recherche `$regex` sur tous les champs concernés
- Ajouter un champ "siren" dans tous les documents.

La deuxième solution n'est pas élégante (duplication de données), mais corrigerait la recherche sans toucher au code source.

**Comment by ldaverio** [comment]
J'ai soumis une solution qui me paraît être meilleure, i.e. compléter la recherche `$text` existante par une recherche `$regex` sur le champ "siret", les deux critères étant reliés par un "ou" logique.

**Comment by FlavieSauvebois** [comment]
Bonjour Laurent, 
Merci pour tes investigations et ta proposition. 
J'en parle avec Georges-André lors de notre prochain point en équipe (le 11/07).

**Comment by ldaverio** [comment]
En fait, si ça ne tenait qu'à moi, je ferais une recherche de type 
"autocomplete", i.e. qui affiche les résultats au fur et à mesure qu'on 
tape (par exemple, à partir de 3 caractères). Certes, ça augmenterait le 
nombre de requêtes sur le backend, mais je trouve que l'ergonomie serait 
plus réactive pour l'utilisateur.

Laurent.


Le 02/07/2024 à 13:33, FlavieSauvebois a écrit :

**Comment by gasilber** [comment]
Déployé en développement pour recette: https://dev-referentiel.apprentissage.onisep.fr

**Comment by FlavieSauvebois** [comment]
Ok pour mise en prod
