### ISSUE TITLE
Suppression de l'UAI sur le siret 88488405700016

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#209]
Hello, 

Il faudrait supprimer l'UAI sur la fiche OF suivante : https://referentiel.apprentissage.onisep.fr/organismes/88488405700016

Je profite de ce ticket pour relancer le sujet. Voir dans quelle mesure il serait possible d'ajouter une fonctionnalité qui me permette de supprimer moi même un UAI sur une fiche OF sans avoir à passer par vous. On en reparle.

**Comment by FlavieSauvebois** [comment]
Cf. issue 174

**Comment by gasilber** [comment]
Issue #174 Réouverte

**Comment by gasilber** [comment]
Fait.

```
org = db.organismes
org.updateOne(
  {"siret":"88488405700016"},
  { $unset: {"uai": ""}}
);
mod = db.modifications
mod.find({"siret": "88488405700016", "changements": {"uai":"0141815X"}})
mod.deleteOne({"siret": "88488405700016", "changements": {"uai":"0141815X"}})
```
