### ISSUE TITLE
Suppression OF 78261516500019 du Référentiel

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#213]
OF à supprimer du Référentiel car il n'accueille pas d'apprentis. Reste dans le Référentiel car présent dans fichier SIFA 2021.

**Comment by ldaverio** [comment]
Données corrigées.

8 lignes supprimée dans le fichier `rofa-data Liste_Etablissements_2021-07-15_RAMSESE_Complement2.csv` et 3 autres fichiers.

**Comment by ldaverio** [comment]
Supprimé de la base :

```
use referentiel
org = db.organismes
org.findOne({'siret': '78261516500019'})
org.deleteOne({'siret': '78261516500019'})
```

**Comment by FlavieSauvebois** [comment]
Je clos ce ticket car l'OF a bien été supprimé.
