### ISSUE TITLE
Ajout de la provenance de l'OF dans le fichier Excel d'export

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#215]
Il faudrait ajouter une colonne avec la provenance de l'OF (SIFA 2021/ Catalogue / Liste DGEFP) dans le fichier Excel d'export. 
Cela permettra de voir si des OF peuvent être supprimés manuellement du Référentiel (OF dont le siret est fermé + SIFA 2021 par ex)

Vérifier aussi si la provenance de l'OF se met à jour dans la fiche OF à partir du moment ou l'OF n'est plus présent dans une source.

**Comment by ldaverio** [comment]
Solution : ajouter une colonne `Références` dans l'export CSV, via le fichier `server/src/common/actions/transformOrganisme.js`.

J'envoie la modification dans Git dès que le système me le permet (pour l'instant, messages d'erreur et echec sur `git commit`).

**Comment by ldaverio** [comment]
J'enlève le label "Done" parce qu'il me semble que le travail n'est pas terminé : j'ai bien rajouté l'info dans l'export lancé via la ligne de commande, mais elle n'apparaît pas dans les exports lancés depuis un navigateur

`api/vi/organismes.xls`

**Comment by ldaverio** [comment]
La version est déployée en développement, il est possible de tester la fonctionnalité.

**Comment by ldaverio** [comment]
Version déployée en production.

**Comment by FlavieSauvebois** [comment]
Merci Laurent pour ce développement.
Je viens de tester rapidement. 
Pour l'OF 39266729100018 je pense qu'il y a une erreur. C'est le nom du réseau qui s’affiche dans la colonne (M) au lieu des sources.
Je ne sais pas à quoi correspond la valeur "mna / catalogue " de la ligne 5296
Si je résume il y a 3 valeurs (sources possibles) : 
- datagouv
- catalogue etablissement
- SIFA-RAMSESE
Est-il possible au niveau du fichier Excel d'avoir ces 3 valeurs au niveau des filtres afin de pouvoir faire des recherches en combinant ces 3 critères ?

Merci

**Comment by ldaverio** [comment]
Bonjour Flavie,

concernant l'OF 39266729100018, l'erreur est dans les données : la raison sociale de l'OF commence vraisemblablement par un caractère "tabulation", et du coup toutes les colonnes se retrouvent poussées d'un cran vers la droite. Je vais corriger le code pour nettoyer ces caractères excédentaires.

Pour les données de la colonne "Référentiel", je reprends à l'identique les valeurs du champ éponyme de MongoDB, en les séparant par des "|". Je ne sais pas ce que signifie "mna / catalogue".

Pour ce qui est du filtrage Excel, je ne suis pas un expert de cet outil, je dois regarder comment fonctionne le filtrage.

**Comment by ldaverio** [comment]
Le problème observé sur l'OF 39266729100018 est corrigé en des et en prod.

**Comment by ldaverio** [comment]
Comme évoqué en réunion tout à l'heure, trier les valeurs du champ "Référentiels" par ordre alphabétique permettra d'appliquer une recherche Excel.

Le système est déployé en dev et en prod.

**Comment by ldaverio** [comment]
L'export reflète directement la collection `organismes` de MongoDB, donc devrait toujours être à jour "en temps réel" par rapport au site web.
