### ISSUE TITLE
Demande Samir - Modification modèle de données

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#220]
Demande envoyée par Samir - à discuter lors de notre prochain point : 
_"Je me permets juste une petite demande au sujet du modèle de donnée du référentiel qui pourrait nous être très utile, serait-il possible à votre niveau d’ajouter dans le champs RELATIONS de l'objet Organisme l’UAI de l’organisme lié ?"_

**Comment by ldaverio** [comment]
Il me semble qu'à l'heure actuelle, le champ `relations` contient une liste d'**objets incorporés** ("embedded documents") et non de **références** à d'autres organismes, créant ainsi une redondance de données. Si un même organisme apparaît plusieurs fois dans la base (une fois en tant que document principal, et éventuellement en plus dans le champ "relations" d'autres objets), il faut s'assurer que toutes ses instances soient synchronisées.

Pour l'instant, et sauf erreur de ma part, seul le champ `uai` peut être modifié via l'application. Si on rajoute un `uai` dans les relations comme demandé, il faudra modifier aussi les traitement d'ajout / modification des UAI pour prendre en compte les objets incorporés.
