### ISSUE TITLE
Mention incorrecte dans une bulle d'aide

### ISSUE THREAD

**Issue by ldaverio** [mission-apprentissage/referentiel#222]
Lors de l'affichage d'un organisme, la bulle d'aide du champ UAI affiche un message incorrect :

<img width="635" alt="Capture d’écran 2024-09-05 à 16 55 45" src="https://github.com/user-attachments/assets/52116bfb-f88c-4026-8580-402f67afb4e6">

(devrait être : `La donnée "UAI" provient de ...`)

**Comment by FlavieSauvebois** [comment]
Bien vu ! 
A corriger par : la donnée "UAI" est validée par un référent dans chaque académie qui peut s'appuyer sur des UAI potentielles issues de différentes sources ou bien renseigner une autre UAI.

**Comment by ldaverio** [comment]
Déployé en dev et en prod.

En passant en revue les autres libellés, je vois que certains ont des points finaux et d'autres non. C'est très mineur, est-ce que je les corrige ou pas ?

**Comment by FlavieSauvebois** [comment]
On peut mettre des points à tout le monde, si ce n'est pas trop long à corriger pour toi. 
De toute façon je suis en train de rebalayer tous les contenus du site. Il va y avoir pas mal de correctifs à faire quand côté ONISEP on aura validé tout ça.

**Comment by ldaverio** [comment]
C'est fait, et déployé en dev et en prod.
