### ISSUE TITLE
OF présent dans le Catalogue qui ne remonte pas dans le Référentiel - 78085695100030

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#244]
Hello, pouvez-vous regarder pourquoi cet OF (78085695100030) qui est portant bien rattaché à une formations dans le Catalogue apprentissage, ne remonte pas dans le Référentiel ?
Et en fonction de la cause, voir si d'autres OF sont concernés ? 

Merci. Flavie

**Comment by FlavieSauvebois** [comment]
Il y a un autre OF concerné : 94927852700021 
Est-ce que vous pourriez regarder ? C'est assez urgent car cela tant que cet OF ne remonte pas dans le Référentiel et qu'il n'est pas fiabilisé, il ne peut pas déclarer ses formations dans Parcoursup.

**Comment by FlavieSauvebois** [comment]
Encore un autre OF : 94885823800025
Il est pourtant bien présent dans le Catalogue. 
Si vous pouviez regarder de manière urgente aujourd'hui. J'aimerai pouvoir traiter tous ces cas avant mon départ en congés demain. C'est urgent car vraiment bloquant du côté de Parcoursup

**Comment by gasilber** [comment]
Après relance SIRENE, les organismes sont présents dans la base.
